name: Main branch pipeline

on:
  push:
    branches:
      - main

jobs:
  critical-tests:
    name: Run Critical Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Critical tests
        run: npx playwright test --config=config/playwright.config.ts
        env:
          BASE_URL: https://naveenautomationlabs.com
          PIPELINE: main
          TEST_SCOPE: critical

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: critical-html-report
          path: config/reports/html/
