name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  smoke-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Smoke tests
        run: npx playwright test --config=config/playwright.config.ts
        env:
          BASE_URL: https://naveenautomationlabs.com
          PIPELINE: pr
          TEST_SCOPE: smoke

      - name: Debug report folders
        if: always()
        run: |
          pwd
          ls -R
          echo "==== REPORTS ===="
          ls -R reports || true

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-html-report
          path: reports/html/
